# Generated by Django 4.2.7 on 2025-03-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArabicAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=2)),
                ('alphabet_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ArabicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diacritics', models.CharField(blank=True, default='', max_length=32)),
                ('position', models.CharField(blank=True, default='', max_length=32)),
                ('word', models.CharField(blank=True, default='', max_length=32)),
                ('bangla', models.CharField(blank=True, default='', max_length=32)),
                ('english', models.CharField(blank=True, default='', max_length=32)),
                ('parts_of_speech', models.CharField(blank=True, default='', max_length=5)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_quran.arabicalphabet')),
            ],
            options={
                'unique_together': {('diacritics', 'letter', 'position')},
            },
        ),
    ]
