# Generated by Django 4.2.13 on 2025-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aya', models.IntegerField(blank=True, null=True)),
                ('sura', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('verse_key', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('simple', models.TextField(blank=True, null=True)),
                ('juz', models.IntegerField(blank=True, null=True)),
                ('hezb', models.IntegerField(blank=True, null=True)),
                ('rub', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('class_name', models.TextField(blank=True, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('code_v3', models.TextField(blank=True, null=True)),
                ('char_type', models.TextField(blank=True, null=True)),
                ('audio', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
