# Generated by Django 4.2.13 on 2025-03-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0003_arabicword_in_quran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabicword',
            name='in_quran',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='learning_quran.quranword'),
        ),
    ]
