# Generated by Django 4.2.13 on 2025-03-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0004_alter_arabicword_in_quran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabicword',
            name='in_quran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_quran.quranword'),
        ),
    ]
