# Generated by Django 4.2.13 on 2025-03-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0005_alter_arabicword_in_quran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arabicword',
            name='in_quran',
        ),
    ]
