# Generated by Django 4.2.13 on 2025-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0007_arabicword_in_quran'),
    ]

    operations = [
        migrations.AddField(
            model_name='arabicalphabet',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
