# Generated by Django 4.2.13 on 2025-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0009_alter_arabicword_in_quran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arabicword',
            name='in_quran',
        ),
        migrations.AddField(
            model_name='arabicalphabet',
            name='alphabet_bangla_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
