# Generated by Django 4.2.13 on 2025-03-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0010_remove_arabicword_in_quran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabicalphabet',
            name='alphabet_bangla_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
