# Generated by Django 4.2.13 on 2025-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0011_alter_arabicalphabet_alphabet_bangla_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arabicalphabet',
            old_name='alphabet_bangla_name',
            new_name='alphabet_banglaname',
        ),
        migrations.AddField(
            model_name='arabicalphabet',
            name='alphabet_phonetics',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
