# Generated by Django 4.2.13 on 2025-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0012_rename_alphabet_bangla_name_arabicalphabet_alphabet_banglaname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabicalphabet',
            name='alphabet_phonetics',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
