# Generated by Django 4.2.13 on 2025-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0013_alter_arabicalphabet_alphabet_phonetics'),
    ]

    operations = [
        migrations.AddField(
            model_name='arabicword',
            name='join_diacritics',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
