# Generated by Django 4.2.13 on 2025-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_quran', '0015_alter_arabicword_diacritics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabicword',
            name='diacritics',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='arabicword',
            name='join_diacritics',
            field=models.CharField(blank=True, default='Words', max_length=32),
        ),
    ]
